### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by WiiNoMa** [Disconnect24/DC24-bot#11]
here are some command suggestions: strike, warn, mute, kick, ban, server info, user info and maybe a stats checker where you can type d!stats and it will say the current dc24 service stats.

**Comment by TheMegaEagle** [comment]
Suggestions will be done here: https://github.com/Disconnect24/DC24-bot/tree/v1.2.0

**Comment by WiiNoMa** [comment]
kthx

**Comment by TheMegaEagle** [comment]
Finished! However, the DC24 service stats command cannot be made until a DC24 API or something of the sort is made.

**Comment by TheMegaEagle** [comment]
rc24 stole idea, im gonna do it now

http://img.themegaeagle.tk/jiqz5y1ln9.png

**Comment by spotlightishere** [comment]
Interesting word choice of "we".
All good, we (as in Disconnect24) will keep in mind to update here as well. Thanks!

**Comment by Artuto** [comment]
Idea stolen successfully ✔️

**Comment by spotlightishere** [comment]
https://github.com/RiiConnect24-Bot/RC24-Bot/commit/fcf59eeffb88cd1d9597f6b375fb45265d163e41

Professional..

That being said, at a meta level for all of @disconnect24, we need some type of service framework handling builds/etc. Sounds like it's worth investigating Jenkins or the like again for that, but for monitoring something'd be nice. We currently go ad-hoc in announcements as do others.

**Comment by Artuto** [comment]
Indeed, if you want you can use mine, its pretty much dead, shoot me DM 👀

**Comment by TheMegaEagle** [comment]
Alright, **now** I’ll work on it 
https://github.com/Disconnect24/DC24-bot/tree/v1.3.0

**Comment by TheMegaEagle** [comment]
Update done, will be merged later
