### ISSUE TITLE
Suggestion, again.

### ISSUE THREAD

**Issue by WiiNoMa** [Disconnect24/DC24-bot#20]
A new command suggestion, hooray.
d!afk 
Make the d!dns command not dm the dns, instead make it go in the chat you put the command in.

**Comment by Apfel** [comment]
d!afk makes no sense
but I can make a pull request for the DNS command

**Comment by TheMegaEagle** [comment]
Label `wontfix` added since Apfels PR has this issue, and yeah like apfel said, afk wont be useful really
