### ISSUE TITLE
an actual database

### ISSUE THREAD

**Issue by TheMegaEagle** [Disconnect24/DC24-bot#23]
so many people have suggested it, that i'm just going to try to do it in v1.5.0 release (weekend of december 29-30th).

I've never done anything with databases besides JSON, so any suggestions on which database to use, and how to set it up? I'd appreciate it.

**Comment by WiiNoMa** [comment]
ill bet apfel will comment "C#"

**Comment by Apfel** [comment]
I don't know how to set it up, but MySQL should be a good choice, right?

**Comment by TheMegaEagle** [comment]
Well, Khan said MySQL for something like a bot is a little unnecessary. However, if someone else can help me set it up, then sure.

**Comment by Apfel** [comment]
What about ReThinkDB or *cough* Redis *cough*

**Comment by TheMegaEagle** [comment]
Like I said before, if you help with setup then I'll look into it.

**Comment by Apfel** [comment]
Well, I'm pretty familiar with Redis, but not really with ReThinkDB, so /shrug

**Comment by TheMegaEagle** [comment]
If nobody suggests anything else before v1.4.0 is released (which should be this weekend), then I'll go with Redis. However, I'm going to leave suggestions open until then.

**Comment by TheMegaEagle** [comment]
I guess we're going with redis. Development will likely start tomorrow, if theres no issues with the patch command. Further development conversation will go on in https://github.com/Disconnect24/DC24-bot/issues/4
